#cursor_shape          Underline
cursor_underline_thickness 1
window_padding_width  0

# Special
foreground           #ced4df
background           #0B0E14

# Black
color0               #1c1f25
color8               #54575d

# Red
color1               #F07178
color9               #ff8087

# Green
color2               #AAD84C
color10              #b9e75b

# Yellow
color3               #E7C547
color11              #f0df8a

# Blue
color4               #36A3D9
color12              #43b0e6

# Magenta (Purple)
color5               #A37ACC
color13              #c79bf4

# Cyan
color6               #74c5aa
color14              #95E6CB

# White
color7               #ced4df
color15              #ced4df

# Cursor
cursor               #ced4df
cursor_text_color    #0B0E14

# Selection highlight
selection_foreground none
selection_background #33363c
