;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[global/wm]
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[bar/top]
tray-position = right
tray-padding =5
width =  100%
height = 30
padding-left =0
padding-right =0
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-top-color = ${colors.background}
border-bottom-color = ${colors.background}
offset-x = 0%
offset-y = 0%
fixed-center = true
line-size = 3
wm-restack = bspwm

modules-left = space filesystem space round-left bspwm round-right space round-left ethernet_status round-right
modules-center = round-left target_status round-right
modules-right = space round-left vpn_status round-right space round-left time round-right space

; ==========================================
; Fuentes (Normalizadas)
; format: font-N = <font-name>:<font-style>:size=<size>;<vertical-offset>
; ==========================================
font-0 = "JetBrainsMono Nerd Font:style=Bold:size=12;3"
font-1 = "Hack Nerd Font:size=14;4"
font-2 = "Hack Nerd Font:size=22;5"
font-8 = Hack Nerd Font:size=22;6
