;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;      __  ___          __      __
;     /  |/  ____  ____/ __  __/ ___  _____
;    / /|_/ / __ \/ __  / / / / / _ \/ ___/
;   / /  / / /_/ / /_/ / /_/ / /  __(__  )
;  /_/  /_/\____/\__,_/\__,_/_/\___/____/
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/round-left]
type = custom/text
content = %{T3}%{T-}
content-foreground = #2b2f37

[module/round-right]
type = custom/text
content = %{T3}%{T-}
content-foreground = #2b2f37

[module/space]
type = custom/text
content = " "

[module/space2]
type = custom/text
content = " "
content-background = #2b2f37

[module/bspwm]
type = internal/bspwm

pin-workspaces = true
inline-mode = true
enable-click = true
enable-scroll = true
reverse-scroll = false

format = <label-state>

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7

label-separator = " "
label-separator-background = #2b2f37

label-focused = "%{T2} %{T-}"
label-focused-foreground = #bf616a
label-focused-padding = 0
label-focused-background = #2b2f37

label-occupied = "%{T2} %{T-}"
label-occupied-foreground = #646870
label-occupied-background = #2b2f37
label-occupied-padding = 0

label-empty = "%{T2} %{T-}"
label-empty-foreground = #646870
label-empty-padding = 0
label-empty-background = #2b2f37

label-urgent = %icon%
label-urgent-foreground = #88C0D0
label-urgent-background = #2b2f37
label-urgent-padding = 0

[module/filesystem]
type = custom/text 
content =" %{T3} %{T-}"
content-padding = 0
click-left = rofi -show drun
content-foreground =  #61afef

[module/time]
type = internal/date
interval = 60
format = <label>
format-background = #2b2f37
date = %{F#888e96}%{T2} %{T-} %H:%M %p%{F-}
time-alt = %{F#61afef}%{T2} %{T-} %a, %d %b %Y%{F-}
label = %date%%time%

[module/ethernet_status]
type = custom/script
format = <label>
format-background = #2b2f37
interval = 2
exec = $HOME/.config/bspwm/scripts/ethernet_status.sh

[module/vpn_status]
type = custom/script
format = <label>
format-background = #2b2f37
interval = 2
exec = $HOME/.config/bspwm/scripts/vpn_status.sh

[module/target_status]
type = custom/script
format = <label>
format-background = #2b2f37
interval = 2
exec = $HOME/.config/bspwm/scripts/target_to_hack.sh
